### ISSUE TITLE
鼠标在ToolBar上滑动的时候会一直在箭头和沙漏中闪烁。

### ISSUE THREAD

**Issue by FistChina** [XuToWei/Unity-ToolbarExtension#1]
![image](https://github.com/XuToWei/ToolbarExtension/assets/29481291/fb105a4a-e558-4eb5-b28f-b0fbaf02609c)
![image](https://github.com/XuToWei/ToolbarExtension/assets/29481291/ee4d141a-250c-4f15-93c0-863722fb1616)
只要在ToolBar上移动就会闪烁

**Comment by XuToWei** [comment]
什么版本的Unity

**Comment by FistChina** [comment]
2022.3.15f1
